security:
    password_hashers:
        App\Entity\User: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            # Remove form_login if you want to use only Google OAuth, or keep both
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: /user/dashboard

            custom_authenticators:
                - App\Security\GoogleAuthenticator

            logout:
                path: app_logout
                target: /login

    access_control:
        - { path: ^/connect/google, roles: PUBLIC_ACCESS }
        - { path: ^/user/dashboard, roles: ROLE_USER }